POST {{$dotenv TextTranslationEndpoint}}/translate?api-version=3.0&from=en&to=de&profanityAction=Marked
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$dotenv Ocp-Apim-Subscription-Key}}
Ocp-Apim-Subscription-Region: {{$dotenv Ocp-Apim-Subscription-Region}}

[
    { 'Text' : 'JSON is fucking great!' }
]
