// Identify the main “talking points” of the text
// Works best with larger documents (up to 5,120 characters)

POST {{$dotenv LanguageEndpoint}}/language/:analyze-text?api-version=2023-11-15-preview
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$dotenv Ocp-Apim-Subscription-Key}}

{
    "kind": "KeyPhraseExtraction",
    "parameters": {
        "modelVersion": "latest"
    },
    "analysisInput":{
        "documents": [
            {
            "id": "1",
            "language": "en",
            "text": "You must be the change you wish 
                    to see in the world."
            },
            {
            "id": "2",
            "language": "en",
            "text": "The journey of a thousand miles 
                    begins with a single step."
            }
        ]
    }
}